### ISSUE TITLE
GraphHelper中，设置点ID的formatter的代码是否存在错误？

### ISSUE THREAD

**Issue by z-yuxie** [nebula-contrib/graph-ocean#14]
io.github.anyzm.graph.ocean.common.GraphHelper#collectGraphField 141行，点ID的formatter设置是否设错了？
当前：
![image](https://user-images.githubusercontent.com/28329410/191233200-0f5793b5-98de-4026-bc2c-bf1a4d0b331f.png)

猜测是否应该是这样：
![image](https://user-images.githubusercontent.com/28329410/191233371-21d6c239-7b20-4c79-98df-529d613a2562.png)

**Comment by Anyzm** [comment]
你好，非常感谢你的参与，我刚看了一下代码，确实是像你所说的，用错方法了，这里应该是顶点id的类型转换，可能这一块目前用得人比较少，所以还没有触及到这个bug，感谢细致的你提出来。
请问你可以单独针对这个bug，帮忙提一个PR吗？

**Comment by Anyzm** [comment]
> io.github.anyzm.graph.ocean.common.GraphHelper#collectGraphField 141行，点ID的formatter设置是否设错了？ 当前： ![image](https://user-images.githubusercontent.com/28329410/191233200-0f5793b5-98de-4026-bc2c-bf1a4d0b331f.png)
> 
> 猜测是否应该是这样： ![image](https://user-images.githubusercontent.com/28329410/191233371-21d6c239-7b20-4c79-98df-529d613a2562.png)

感谢你的指点，目前main分支已修复，近期会推送到中央仓库
