### ISSUE TITLE
切换 spcae异常。

### ISSUE THREAD

**Issue by linfahe** [nebula-contrib/graph-ocean#17]
执行test方法：[main] ERROR io.github.anyzm.graph.ocean.session.NebulaSessionWrapper - 更新nebula异常 code:-1004, msg:SyntaxError: syntax error near `execute', nGql:execute first_space ; UPSERT VERTEX  "UR123"  SET user.user_name=张三,user.user_no=UR123; 
本人环境 3.0，使用 jdk 17运行。
发现问题：
1、execute first_space ;   应该是 use ；
2、UPSERT VERTEX  "UR123"  SET user.user_name=张三,user.user_no=UR123;  语法错误，
官网语法规则： 
UPSERT VERTEX ON <tag> <vid>
SET <update_prop>
[WHEN <condition>]
[YIELD <output>]

亲测： UPSERT VERTEX on user   "UR123"  SET user.user_name="张三",user.user_no="UR123"; 可以运行。

后续 有考虑 集成到 springboot 中，开发一个 start，自动装配？

**Comment by Anyzm** [comment]
springboot只需要自己写一个config类就好了，在生产实践的文档里面有写，starter开发的意义不大，目前没有计划。

1、execute first_space ; 应该是 use ；这个可以提供具体类和方法吗？
2、语法问题2.x的版本是支持的，可能3.x语法有调整，有时间再改一下，或者您这边方便的话也可以帮忙提一个PR

**Comment by linfahe** [comment]
io.github.anyzm.graph.ocean.mapper.NebulaGraphMapper.SQL

**Comment by Anyzm** [comment]
> io.github.anyzm.graph.ocean.mapper.NebulaGraphMapper.SQL

好的，谢谢
在这个文档里面的初始化示例，拷贝过去改一改就适配springboot的项目
https://github.com/nebula-contrib/graph-ocean/blob/main/detailed_introduction.md

**Comment by linfahe** [comment]
好的，谢谢

**Comment by Anyzm** [comment]
目前已经发布3.0.1
