### ISSUE TITLE
Problem with anotation @GraphProperty

### ISSUE THREAD

**Issue by tranquocnhat** [nebula-contrib/graph-ocean#21]
![image](https://user-images.githubusercontent.com/23132487/236637380-ef7895f7-bb4f-480f-86f2-2ec47c105d49.png)
![Screenshot 2023-05-07 000256](https://user-images.githubusercontent.com/23132487/236637515-c42fd629-ff21-4dbb-9754-fc8deafb51ab.png)
![Screenshot 2023-05-07 000314](https://user-images.githubusercontent.com/23132487/236637523-390db837-5418-43be-89f9-f8e105a35c66.png)
I just use GraphProperty anotation but i only can map data when rename field in class to same tag name in nebula,
as my case area and hash_ward field i keep same name in tag and can map.
I using graph-ocean 3.0.1 nebula 3.0.0 loombok 1.18.12

**Comment by Anyzm** [comment]
感谢您的来件，邮件已收到。

**Comment by tranquocnhat** [comment]
![image](https://user-images.githubusercontent.com/23132487/236637677-e8ec4e68-4072-4f36-bfd6-8e7fffd11c6a.png)

**Comment by Anyzm** [comment]
hi，i think first you should define the dataType for @GraphProperty，eg： @GraphProperty(value = "wardname", dataType = GraphDataTypeEnum.STRING)，because the default dataType is GraphDataTypeEnum.NULL。
hower，I don't know why the area attribute worked at the moment，maybe it is a bug。

**Comment by Anyzm** [comment]
> ![image](https://user-images.githubusercontent.com/23132487/236637677-e8ec4e68-4072-4f36-bfd6-8e7fffd11c6a.png)

excuse me ，Has this problem been solved?

**Comment by tranquocnhat** [comment]
@Anyzm oh my team build owner adapter for use nebula alternative graph-ocean, and i dont use this lib

**Comment by Anyzm** [comment]
> @Anyzm oh my team build owner adapter for use nebula alternative graph-ocean, and i dont use this lib

ok，so sorry！
