### ISSUE TITLE
你好，有更详尽的使用文档吗？

### ISSUE THREAD

**Issue by hejiahuichengxuyuan** [nebula-contrib/graph-ocean#3]

**Comment by Anyzm** [comment]
这个刚上传不久，后续计划会上传maven中央仓库，也会出详细一点的使用文档。

**Comment by wey-gu** [comment]
> 这个刚上传不久，后续计划会上传maven中央仓库，也会出详细一点的使用文档。

ref: https://github.com/nebula-contrib/nebula-jdbc/pull/30 for maven repo :)
