### ISSUE TITLE
边的保存

### ISSUE THREAD

**Issue by sjpgit1** [nebula-contrib/graph-ocean#4]
大佬，您好，请问保存无属性的边应该怎么做？用upsert语句必须是有属性的边吧

**Comment by Anyzm** [comment]
目前保存边和顶点都是用upsert的，无属性的边暂时没试过，可以用ngql自己试试，不过一般就算没有任何业务属性不是应该也存一存创建或者修改时间吗？

**Comment by sjpgit1** [comment]
> 目前保存边和顶点都是用upsert的，无属性的边暂时没试过，可以用ngql自己试试，不过一般就算没有任何业务属性不是应该也存一存创建或者修改时间吗？

好的，多谢。我还有个小问题，请问节点的属性格式为timestamp时应该怎么处理呢？我看注入的ngql语句都转为了string格式

**Comment by Anyzm** [comment]
属性注解：GraphProperty的dataType可以指定字段的类型，GraphDataTypeEnum.TIMESTAMP即可

**Comment by sjpgit1** [comment]
> 

ok，了解。请问大佬，目前支持查询里使用属性引用符吗？  $$、$-和$^
