### ISSUE TITLE
查询结果乱码了

### ISSUE THREAD

**Issue by z921887787** [nebula-contrib/graph-ocean#5]
![1652083413](https://user-images.githubusercontent.com/44262267/167366909-ccfab0ae-5cdc-4791-8955-499ed70188f7.jpg)

**Comment by Anyzm** [comment]
看样子这个不是乱码，而是传输编码，QueryResult.get的时候会有解码操作

**Comment by z921887787** [comment]
> 看样子这个不是乱码，而是传输编码，QueryResult.get的时候会有解码操作

那咋办咧，查询出来的结果想封装成Java Bean返回给前端，现在不知道咋弄了。

**Comment by Anyzm** [comment]
可以参考NebulaGraphMapper类里的List<T> executeQuerySql(String sql, Class<T> clazz) throws NebulaException 

如果没有特殊的格式转化的话，直接调用QueryResult.getEntities方法即可

**Comment by z921887787** [comment]
> 可以参考NebulaGraphMapper类里的List executeQuerySql(String sql, Class clazz) throws NebulaException
> 
> 如果没有特殊的格式转化的话，直接调用QueryResult.getEntities方法即可
好的，感谢大佬！
