### ISSUE TITLE
支持3.0吗

### ISSUE THREAD

**Issue by gitxulang** [nebula-contrib/graph-ocean#9]
最新版本都是3.0了，现在orm能支持吗

**Comment by Anyzm** [comment]
感谢您的来件，邮件已收到。

**Comment by Anyzm** [comment]
> 最新版本都是3.0了，现在orm能支持吗

理论上只需要替换pom中client的版本就ok，但由于我们目前没有3.0的环境，建议自己替换之后在测试环境先泡一下业务场景。
也欢迎大佬提交新的分支的PR（3.0可以作为一个单独的分支）
